### ISSUE TITLE
setState(const status)

### ISSUE THREAD

**Issue by stritti** [YuriiSalimov/RelayModule#1]
I think it could  be helpful to have a switch-Method using boolean parameter. Something like:

``` 
void RelayModule::setState(const boolean flag) {
   write((flag ? this->onSignal : this->offSignal );
}
```

**Comment by suoapvs** [comment]
Done!

Regards, Yurii.

**Comment by stritti** [comment]
Awesome, thanks for fast implementation:
https://github.com/YuriiSalimov/RelayModule/commit/ada60cf09bb81ec81eb15b111fdda6dbeca0674b

Regards, Stephan
